version: '2'

services:
    
    nginx:
        build: .
        image: "local-nginx"
        container_name: nginx
        ports:
            - 443:443
            - 80:80
        expose:
            - 80
            - 443
        volumes:
            - ./confs/:/etc/nginx/conf.d:ro
            - ./projects/:/usr/share/nginx
        restart: always